name: ci action

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: git pull
        uses: actions/checkout@v4
        with:
          ref: master

      - name: install QEMU
        uses: docker/setup-qemu-action@v3

      - name: install buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: rosven9856
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: UBUNTU_VERSION=22.04
          push: true
          tags: |
            rosven9856/speedtestnet:${{ github.event.release.tag_name }}
            rosven9856/speedtestnet:latest

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Github. Creating new release speedtestnet

            Repository: ${{ github.repository }}
            Release: ${{ github.event.release.tag_name }}

            See details: https://github.com/${{ github.repository }}/releases
