name: tests

on:
  pull_request: ~
  push:
    branches: ['*.*.x', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git pull
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: rosven9856
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push in dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: UBUNTU_VERSION=22.04
          push: false
          tags: |
            rosven9856/speedtestnet:testing
            rosven9856/speedtestnet:latest
